---

# https://hub.docker.com/r/library/python/tags/
image: python:3.9.12-buster

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install -U virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -Ur requirements.txt
  - echo isort $(isort --version-number)
  - black --version
  - flake8 --version
  - pylint --version
  - yamllint --version

build:
  stage: build
  except: [tags]
  script:
    - echo check ...
    - isort --check --diff read_yaml.py employees/*.py utils/*.py tests/*.py
    - black --check read_yaml.py employees/*.py utils/*.py tests/*.py
    - pylint read_yaml.py employees/*.py utils/*.py tests/*.py
    - yamllint --strict .github/workflows/*.yml .*.yml *.yml tests/*.yaml
    - python setup.py check
    - echo test ...
    - pytest -v --cov-report term-missing --cov=employees tests/
    - echo run ...
    - python -m read_yaml -h
    - python -m read_yaml --version
    - python -m read_yaml -v tests/test.yaml

pages:
  stage: deploy
  only: [master]
  except: [tags]
  script:
    - echo document ...
    - pytest -v --html=cover/report.html --cov=employees
        --cov-report=html:cover tests/
    - coverage html -d cover employees/employees.py
    - (cd docs; make html)
    - python setup.py clean
    - python setup.py sdist --dist-dir=target/dist
    - python setup.py build --build-base=target/build
    - mv target/docs/html public
  artifacts:
    paths:
      - public
      - target/dist/*.tar.gz
