---

image: python:3.10.4-buster

pipelines:
  default:
    - step:
        name: build all
        caches:
          - pip
        condition:
          changesets:
            includePaths:
              - Makefile
              - requirements.txt
              - "*.py"
              - "*.rst"
              - "docs/**"
              - "employees/**"
              - "tests/**"
              - "utils/**"
        script:
          - uname -a
          - apt-get update && apt-get install -y make python3-yaml
          - pip install -Ur requirements.txt
          - python --version
          - pip --version
          - echo isort $(isort --version-number)
          - black --version
          - flake8 --version
          - pylint --version
          - yamllint --version
          - make clean all
        artifacts:
          - target/docs/html/**
